# fly.toml app configuration file generated for websocket-games-backend on 2024-04-21T21:12:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'websocket-games-backend'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  HOSTNAME = "0.0.0.0"